name: uthix_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  dio: ^5.8.0+1
  flutter_image_compress: ^2.4.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  table_calendar: ^3.2.0
  time: ^2.1.5
#  razorpay_flutter: ^1.4.0
  cached_network_image: ^3.4.1

  file_picker: ^9.0.2
  http: ^1.3.0
  webview_flutter: ^4.10.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^4.2.1

  firebase_core: ^1.19.0

  url_launcher: ^6.3.1


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/registration/book.png"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/registration/
    - assets/login/
    - assets/instructor/
    - assets/account_profile/
    - assets/files_icons/
    - assets/icons/
    - assets/Seller_dashboard_images/
    - assets/Student_Home_icons/
    - assets/Student_BooksImages/
    - assets/classroom_icons/
    - assets/Modern_Tools/
    - assets/Payments/
    - assets/ecommerce/
    - assets/buyplan/
